# Generated by Django 4.1.3 on 2022-12-14 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_ashar_jadwalsholat_jadwals_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwalsholat',
            options={'ordering': ['-tanggal'], 'verbose_name_plural': 'JadwalSholat'},
        ),
        migrations.RemoveField(
            model_name='jadwalsholat',
            name='imam',
        ),
        migrations.RemoveField(
            model_name='jadwalsholat',
            name='jadwals',
        ),
        migrations.AddField(
            model_name='jadwalsholat',
            name='jadwal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jadwalsholat',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.kategori'),
        ),
        migrations.AddField(
            model_name='jadwalsholat',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jadwalsholat',
            name='tanggal',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Artikel',
        ),
    ]
