# Generated by Django 4.1.3 on 2022-12-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_jadwalsholat_options_remove_jadwalsholat_imam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalsholat',
            name='tanggal',
            field=models.DateField(blank=True, null=True, verbose_name=True),
        ),
    ]
