# Generated by Django 4.1.3 on 2022-12-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_apijadwal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoaIslami',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('doa', models.TextField()),
                ('ayat', models.TextField()),
                ('latin', models.TextField()),
                ('artinya', models.TextField()),
            ],
        ),
    ]
